function Ge = extended_gravity_terms(in1,in2)
%EXTENDED_GRAVITY_TERMS
%    GE = EXTENDED_GRAVITY_TERMS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    02-Apr-2019 18:01:55

Lf = in2(5,:);
Lt = in2(1,:);
g = in2(13,:);
lcmT = in2(4,:);
lcmf = in2(6,:);
lcmt = in2(2,:);
mT = in2(9,:);
mf = in2(11,:);
mt = in2(7,:);
q1 = in1(5,:);
q31 = in1(1,:);
q32 = in1(2,:);
q41 = in1(3,:);
q42 = in1(4,:);
Ge = [g.*(Lt.*mT.*sin(q1+q31-q41)+Lt.*mf.*sin(q1+q31-q41).*2.0+Lt.*mt.*sin(q1+q31-q41).*2.0-lcmt.*mt.*sin(q1+q31-q41)+Lf.*mT.*sin(q1+q31)+Lf.*mf.*sin(q1+q31).*2.0+Lf.*mt.*sin(q1+q31)-lcmf.*mf.*sin(q1+q31));-g.*(lcmt.*mt.*sin(q1+q32-q42)+Lf.*mt.*sin(q1+q32)+lcmf.*mf.*sin(q1+q32));-g.*(Lt.*mT.*sin(q1+q31-q41)+Lt.*mf.*sin(q1+q31-q41).*2.0+Lt.*mt.*sin(q1+q31-q41).*2.0-lcmt.*mt.*sin(q1+q31-q41));g.*lcmt.*mt.*sin(q1+q32-q42);-g.*(lcmT.*mT.*sin(q1)-Lt.*mT.*sin(q1+q31-q41)-Lt.*mf.*sin(q1+q31-q41).*2.0-Lt.*mt.*sin(q1+q31-q41).*2.0+lcmt.*mt.*sin(q1+q31-q41)+lcmt.*mt.*sin(q1+q32-q42)-Lf.*mT.*sin(q1+q31)-Lf.*mf.*sin(q1+q31).*2.0-Lf.*mt.*sin(q1+q31)+Lf.*mt.*sin(q1+q32)+lcmf.*mf.*sin(q1+q31)+lcmf.*mf.*sin(q1+q32));0.0;0.0];
