function Be = extended_input_Matrix(in1,in2)
%EXTENDED_INPUT_MATRIX
%    BE = EXTENDED_INPUT_MATRIX(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    02-Apr-2019 18:01:55

Be = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0],[7,4]);
