function B = input_Matrix(in1,in2)
%INPUT_MATRIX
%    B = INPUT_MATRIX(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    02-Apr-2019 18:01:54

B = reshape([1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0],[5,4]);
