function task_vel = taskVel(in1,in2,in3)
%TASKVEL
%    TASK_VEL = TASKVEL(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    02-Apr-2019 18:01:55

Lf = in3(5,:);
Lt = in3(1,:);
dq1 = in2(5,:);
dq31 = in2(1,:);
dq32 = in2(2,:);
dq41 = in2(3,:);
dq42 = in2(4,:);
lcmT = in3(4,:);
lcmf = in3(6,:);
lcmt = in3(2,:);
q1 = in1(5,:);
q31 = in1(1,:);
q32 = in1(2,:);
q41 = in1(3,:);
q42 = in1(4,:);
task_vel = reshape([cos(q1+q31-q41).*(Lt-lcmt).*(dq1+dq31-dq41),sin(q1+q31-q41).*(Lt-lcmt).*(dq1+dq31-dq41),dq1.*(Lt.*cos(q1+q31-q41)+cos(q1+q31).*(Lf-lcmf))+dq31.*(Lt.*cos(q1+q31-q41)+cos(q1+q31).*(Lf-lcmf))-Lt.*dq41.*cos(q1+q31-q41),dq1.*(Lt.*sin(q1+q31-q41)+sin(q1+q31).*(Lf-lcmf))+dq31.*(Lt.*sin(q1+q31-q41)+sin(q1+q31).*(Lf-lcmf))-Lt.*dq41.*sin(q1+q31-q41),dq1.*(Lt.*cos(q1+q31-q41)+Lf.*cos(q1+q31)-lcmT.*cos(q1))+dq31.*(Lt.*cos(q1+q31-q41)+Lf.*cos(q1+q31))-Lt.*dq41.*cos(q1+q31-q41),dq1.*(Lt.*sin(q1+q31-q41)+Lf.*sin(q1+q31)-lcmT.*sin(q1))+dq31.*(Lt.*sin(q1+q31-q41)+Lf.*sin(q1+q31))-Lt.*dq41.*sin(q1+q31-q41),dq1.*(Lt.*cos(q1+q31-q41)+Lf.*cos(q1+q31)-lcmf.*cos(q1+q32))+dq31.*(Lt.*cos(q1+q31-q41)+Lf.*cos(q1+q31))-Lt.*dq41.*cos(q1+q31-q41)-dq32.*lcmf.*cos(q1+q32),dq1.*(Lt.*sin(q1+q31-q41)+Lf.*sin(q1+q31)-lcmf.*sin(q1+q32))+dq31.*(Lt.*sin(q1+q31-q41)+Lf.*sin(q1+q31))-Lt.*dq41.*sin(q1+q31-q41)-dq32.*lcmf.*sin(q1+q32),dq1.*(Lt.*cos(q1+q31-q41)-lcmt.*cos(q1+q32-q42)+Lf.*cos(q1+q31)-Lf.*cos(q1+q32))+dq31.*(Lt.*cos(q1+q31-q41)+Lf.*cos(q1+q31))-dq32.*(lcmt.*cos(q1+q32-q42)+Lf.*cos(q1+q32))-Lt.*dq41.*cos(q1+q31-q41)+dq42.*lcmt.*cos(q1+q32-q42),dq1.*(Lt.*sin(q1+q31-q41)-lcmt.*sin(q1+q32-q42)+Lf.*sin(q1+q31)-Lf.*sin(q1+q32))+dq31.*(Lt.*sin(q1+q31-q41)+Lf.*sin(q1+q31))-dq32.*(lcmt.*sin(q1+q32-q42)+Lf.*sin(q1+q32))-Lt.*dq41.*sin(q1+q31-q41)+dq42.*lcmt.*sin(q1+q32-q42),dq1.*(Lt.*cos(q1+q31-q41)-Lt.*cos(q1+q32-q42)+Lf.*cos(q1+q31)-Lf.*cos(q1+q32))+dq31.*(Lt.*cos(q1+q31-q41)+Lf.*cos(q1+q31))-dq32.*(Lt.*cos(q1+q32-q42)+Lf.*cos(q1+q32))-Lt.*dq41.*cos(q1+q31-q41)+Lt.*dq42.*cos(q1+q32-q42),dq1.*(Lt.*sin(q1+q31-q41)-Lt.*sin(q1+q32-q42)+Lf.*sin(q1+q31)-Lf.*sin(q1+q32))+dq31.*(Lt.*sin(q1+q31-q41)+Lf.*sin(q1+q31))-dq32.*(Lt.*sin(q1+q32-q42)+Lf.*sin(q1+q32))-Lt.*dq41.*sin(q1+q31-q41)+Lt.*dq42.*sin(q1+q32-q42)],[2,6]);
